BEGIN TRAN
    CREATE TABLE #TPARTNERTMP (
        CONTRACTNUMBER VARCHAR(400),
        CONTRACTID BIGINT,
        OLDPARTNERID BIGINT,
        NEWPARTNERID BIGINT,
         NEWCOMPANYCODE VARCHAR(400), 
        NEWCOMPANY VARCHAR(400)                  
    )

    INSERT INTO #TPARTNERTMP VALUES('xxx', (SELECT CONTRACTID FROM TCONTRACT WHERE CONTRACTNUMBER =  'xxx' ), (SELECT LESSEEID FROM TCONTRACT WHERE CONTRACTNUMBER = 'xxx'  ),  (SELECT PARTNERID FROM TPARTNER WHERE COMPANYCODE = 'yyy'),  (SELECT COMPANYCODE FROM TPARTNER WHERE COMPANYCODE = 'yyy'),  (SELECT COMPANY FROM TPARTNER WHERE COMPANYCODE = 'yyy'))
                
         DECLARE partnerCursor CURSOR FOR
         SELECT CONTRACTNUMBER, CONTRACTID, OLDPARTNERID, NEWPARTNERID, NEWCOMPANYCODE, NEWCOMPANY
         FROM #TPARTNERTMP
                
        DECLARE 
            @CONTRACTNUMBER VARCHAR(400),
            @CONTRACTID BIGINT,
            @OLDPARTNERID BIGINT,
            @NEWPARTNERID BIGINT,
            @NEWCOMPANYCODE VARCHAR(400), 
            @NEWCOMPANY VARCHAR(400)

            OPEN partnerCursor
            FETCH NEXT FROM partnerCursor INTO @CONTRACTNUMBER, @CONTRACTID, @OLDPARTNERID, @NEWPARTNERID, @NEWCOMPANYCODE, @NEWCOMPANY
                WHILE (@@FETCH_STATUS = 0)
                BEGIN
                PRINT 'Change data for ' + @CONTRACTNUMBER + ' from ' + cast(@OLDPARTNERID AS nvarchar) + ' to ' + cast(@NEWPARTNERID AS nvarchar) 
                if (@OLDPARTNERID IS NULL)
                    GOTO CONT

                UPDATE TCONTRACT SET LESSEECOMPANYCODE = @NEWCOMPANYCODE, LESSEEID = @NEWPARTNERID WHERE LESSEEID = @OLDPARTNERID AND CONTRACTID = @CONTRACTID;
                UPDATE TLesseeLessorDependency SET LesseeCompanyCode = @NEWCOMPANYCODE, LesseeId = @NEWPARTNERID WHERE LesseeId = @OLDPARTNERID AND CONTRACTID = @CONTRACTID;
                UPDATE TLeaseRecord SET PARTNERID = @NEWPARTNERID, COMPANY = @NEWCOMPANY WHERE PARTNERID = @OLDPARTNERID AND CONTRACTNUMBER= @CONTRACTNUMBER;
                UPDATE TLESSEEPOSTINGRECORD SET PARTNERID = @NEWPARTNERID, COMPANY = @NEWCOMPANY WHERE PARTNERID = @OLDPARTNERID AND CONTRACTNUMBER= @CONTRACTNUMBER;
                UPDATE TIMPORTLOG SET PARTNERID = @NEWPARTNERID WHERE PARTNERID = @OLDPARTNERID AND CONTRACTNUMBER = @CONTRACTNUMBER;
                UPDATE TIMPORTMESSAGE SET PARTNERCOMPANYCODE = @NEWCOMPANYCODE, PARTNERID = @NEWPARTNERID WHERE PARTNERID = @OLDPARTNERID AND CONTRACTNUMBER = @CONTRACTNUMBER;
                        
                        CONT:
                FETCH NEXT FROM partnerCursor INTO @CONTRACTNUMBER, @CONTRACTID, @OLDPARTNERID, @NEWPARTNERID, @NEWCOMPANYCODE, @NEWCOMPANY
                END
            CLOSE partnerCursor
            DEALLOCATE partnerCursor
            PRINT 'Contracts with NULL as PartnerID are to be skipped.'
            DROP TABLE #TPARTNERTMP;
COMMIT TRAN
GO
